- lib/api/bulk.js
- lib/api/metadata.js
If bulk batch result polling timeouts, it shows error "Polling time out" and no job id or batch id was returned. It is difficult to watch the executed result afterward.
> Polling timeout message is not descriptive so that cannot continue the bulk batch

- lib/api/bulk.js
- lib/connection.js
- test/bulk.test.js
If I instantiate a Connection using a refresh token, and then use the Connection to bulk load records, I receive an error if the access token is invalid. 
When the access token has expired the returned HTTP status code is 400, not 401 as expected. This causes the Connection to return an error rather then trying to fetch another access token.
> Submitting batches via bulk.load when access key has expired errors out

- lib/api/bulk.js
our server's callback is never called when there's a job error
> on job error, it was not calling callback with error

- lib/api/bulk.js
Do not close job when polling timeout error occurred in Bulk#load()
> Remain bulk job opened even if polling timeout occurred

- lib/api/metadata.js
This change adds a poll event to the polling method in the Metadata class. It's useful for when you need constant updates during a deployment on the current statues.
> add emit poll event when polling a deploy

- lib/api/bulk.js
If we call 'Bulk#load()' with operation `hardDelete`, it will raise job error
```
InvalidJob: Unable to parse Job
```
> Bulk hard delete is not working, causes job error

- Gruntfile.js
- lib/api/bulk.js
- lib/api/metadata.js
- lib/browser/canvas.js
- lib/browser/request.js
- lib/cli/repl.js
- lib/query.js
- lib/record-stream.js
- lib/transport.js
- package.json
- test/query.test.js
JSforce has a part that manipulates stream in "streams1" style. To make it much stable, it needs to remove these code and replace it to newer version of stream implementation "[streams3](https://github.com/joyent/node/issues/5860)"
> Use stream3 for better stability

- .travis.yml
As TravisCI supports environment variable now, it is not required to embed the environment variable info even in encrypted way.
> Remove encrypted env from .travis.yml Setting

- package.json
[npm >= 2.10.0](https://github.com/npm/npm/releases/tag/v2.10.0) warns when there is no license field in the package.json. This sets the license field to be MIT.
> License in package.json

- lib/api/bulk.js
This emits the error event on the returned stream for polling a batch and for
loading a query. Before, execution would just hang indefinitely. Resolves #227.
> Bubble up errors for bulk

- test/analytics.test.js
`report.instance().retrieve()` sometime returns a result with reportMetadata=null
> Fix failure of report async execution test code

- lib/api/streaming.js
This resolves #224 by returning the subscription object for the streaming api. This does break the existing chaining api, but it is unlikely the chaining feature is used, so the impact of breaking this API _should_ be minimal.
> Return subscription object

- lib/api/bulk.js
There are some options supported by the Bulk API that are missing from jsforce. This simple commit adds concurrencyMode, which allows users to toggle between Parallel (the default in Salesforce) and Serial.
From the Salesforce docs:
**Parallel**: Process batches in parallel mode. This is the default value.
**Serial**: Process batches in serial mode. Processing in parallel can cause database contention. When this is severe, the job may fail. If you're experiencing this issue, submit the job with serial concurrency mode. This guarantees that batches are processed one at a time. Note that using this option may significantly increase the processing time for a job.
Here's the full list of supported options:
https://developer.salesforce.com/docs/atlas.en-us.api_asynch.meta/api_asynch/asynch_api_ …
> Add Bulk API Job option to change concurrency mode

- lib/api/bulk.js
To pass options other than external id in upsert operation, options must be passed to batch job options in every bulkload operation.
In order to keep the current behavior the options parameter also can be omittable.
> Accept bulkload options in all type of operation

- build/jsforce-core.js
- lib/api/bulk.js
This fix a problem of not running assignment rule. However, you must specify the assignment rule to be executed.
> Possible to set an assignment rule id to be run on bulkInsert

- lib/connection.js
https://github.com/jsforce/jsforce/blob/master/lib/connection.js#L545
`conn.sobject(type).retrieve(undefined);` will result in the describe operation for that type being executed.  The result will be the JSON object that describes the type.  This should either throw or return undefined.
> describe instead of retrieve

- lib/cli/cli.js
In `/node_modules/promise/lib/core.js:8`
```
if (typeof fn !== 'function') throw new TypeError('not a function')
^
TypeError: not a function
```
> REPL .register fails

- lib/soap.js
Here is a fix for this error when calling a SOAP method:
{ [soapenv:Client: The entity name must immediately follow the '&' in the entity reference.] name: 'soapenv:Client', errorCode: 'soapenv:Client' }
> Fix toXML function to handle values with XML special characters

- lib/record-stream.js
In 1.5.0, record stream map function and filter function doesn't yield any value to piped downstream.
> RecordStream#map() and RecordStream#filter is broken

- .travis.yml
In Travis CI, include Node.js 4.2 and stable version to the test target.
> Add node.js 4.2 and stable to target

- lib/api/bulk.js
- lib/promise.js
IE9 won't allow you to use the reserve word `catch` as a function, so instead I'm using the `fail` alias set up in lib/promise.js. I'm not sure if there are other issues with IE 9, but this was the one reported.
Closes #283
> Use fail alias for promise.catch

- lib/api/streaming.js
- test/streaming.test.js
After Spring'16, the generic streaming API seems not working in the former endpoint. Fixing to connect to durable streaming endpoint to work correctly. (Not implemented replay option passing yet).
> Fix streaming api update from spring 16

- .travis.yml
Fix wrong cache directory naming `node-modules` to `node_modules`
> Fix travis.yml cache setting for node_modules

- .travis/setup.sh
As the phantomjs bitbucket download url hits rate limit frequently, change to github-hosted url by medium.
> Change download url from bitbucket to github

- lib/connection.js
- lib/transport.js
- test/connection-meta.test.js
From visualforce page it shows following error in conslole.
```
XMLHttpRequest cannot load https://login.salesforce.com/id/00D80000000L4RvEAK/00580000001hc9JAAQ?forma…
Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
Origin 'https://mashmatrix-demo01-dev-ed--c.na6.visual.force.com' is therefore not allowed access.
```
It should use JSONP transport, but not used correctly.
> Connection#identity() returns XHR error in non-proxied environment

- lib/connection.js
Use canvas transport when the connection has signedRequest and canvas transport is supported.
> Fix canvas request failing without using proper transport

- lib/connection.js
- lib/query.js
When calling query API the http request headers can be modified by application developers - like `Sforce-Query-Options` headers.
Closes #248.
> Enable to pass options in query methods to modify http headers in request

- lib/connection.js
- lib/oauth2.js
As the revoke service URL doesn't provide CORS headers, use JSONP to request the access token revocation in browser environment.
Closes #263.
> OAuth2 revoke token request in browser environment

- test/bin/run-test
As the test case fails frequently (especially session related tests requires OAuth2 dancing, which requires scraping via phantomjs, and not stable in automation), add retry option in mocha.
> Enable retrying in tests

- test/sobject.test.js
Sometimes the query length might hit to the entity limit, so reduce the test query length.
> Fix test to exclude owner info in asterisk query to reduce query length

- lib/api/streaming.js
- package.json
On new installs, calls to `Streaming#_getFayeClient` cause an uncaught `TypeError: Cannot read property 'NodeHttp' of undefined`. This is because [the latest minor release of Faye was refactored so that Faye.Transport is no longer exposed](https://github.com/faye/faye/commit/c7e4163638ac73e55c258e291694a298d0469635#diff-4ac32a78649ca5bdd8e0ba38b7006a1eR4). This PR modifies `_getFayeClient` so instead of modifying the `NodeHttp` prototype, the function sets batching to `false` on the transport object for each new Faye client created.
I went ahead and updated the Faye version in `package.json` to make the usage more clear, even though the semver specifications are equivalent.
> Transport is no longer exposed in Faye 1.2

- lib/query.js
The issue here is that we expect a JSON object for the "includes".
We iterate through all the sub queries we wish to include, and call "include" recursively with the correct arguments.
```javascript
if (_.isObject(childRelName)) {
var includes = childRelName;
for (var crname in includes) {
var config = includes[crname];
this.include(crname, config.conditions, config.fields, config);
}
return;
}
```
In the end we wish to append them to a list, but the check is if the "includes" has a false value.
Then we assume "includes" is an array so we want to push the configuration we just built.
The assumption fails when the "includes" is a JSON object, which is what we expect.
Old:
```js
this._config.includes = this._config.includes || [];
this._config.includes.push(childConfig);
```
By checking if …
> includes subquery behave properly and added sort fixes #11

- lib/connection.js
- lib/sobject.js
This is to follow up the previous pull request https://github.com/jsforce/jsforce/pull/494. I've made more improvements based on @stomita comments, and set headers for more operations.
> Use headers for requestGet, retrieve, identity, find and describe calls

- lib/cli/repl.js
REPL completion is not working in node v6 or higher
> Fix repl completion in node v6

- lib/api/bulk.js
allows code that is tracking multiple batches to easily determine which batch has timed out
> add batchId and jobId to PollingTimeout error object

- lib/browser/jsonp.js
In an environment such as React Native the ```window``` object is defined, but the ```document``` object is not, making the JSONP support not function correctly.  This PR adds a check to ```document``` as well. There shouldn't be any regressions from this change.
> JSONP Transport 'supported' also checks for document

- .travis.yml
- package.json
As 0.12 maintenance will end in the end of 2016, remove the support of 0.12 in JSforce.
> Remove support of Node.js 0.12

- README.md
- test/bin/run-test
- test/package/JSforceTestSuite/permissionsets/JSforceTestPowerUser.permissionset
This PR:
- Adds a permission set needed to deploy the package for new developer orgs (DelegatedTwoFactor), without this the package deploy will fail on a fresh ```org-setup```.
- Adds a section to the ```README``` about how to run the tests.
- Makes the call to mocha in ```run-test``` absolute so that if you run it directly it will work, whereas right now it only works when run through ```npm test```.
> Test improvements & doc

- lib/api/analytics.js
- test/analytics.test.js
I tried to follow as much prior art as possible.  I wasn't sure how to add a test for this so I didn't.  If you have any documentation on writing a test for it I'd be happy to do so.
> Adding the ability to destroy reports via the analytics API

- lib/connection.js
- lib/oauth2.js
- lib/transport.js
This implements the ability to specify a proxy programmatically when using jsforce on the server as a node module. This pull request piggybacks on the `proxyUrl` parameter and passes it through to the `request` module's `proxy` parameter. This also provides a fix for jsforce/jsforce#1.
The issue for us with using the `HTTP_PROXY` environment variable is that then all outgoing requests (at least using the `request` library) would be forced to use the proxy. This is because the `request` library also respects the `HTTP_PROXY` environment variable (https://github.com/request/request#controlling-proxy-behaviour-using-environment-variables). In our use case, we want to force all jsforce requests to go through a proxy but we don't necessarily want all other requests in that same node process to …
> Allow the ability to programmatically specify a proxy when using the library in node.

- lib/connection.js
Apex/Bulk API can use the Id field as an external Id. In those cases, you can't provide a value, and thus it fails with JSForce due to this error condition. Also, (although it's not a good idea in my opinion), you could have a blank value as an External Id.
> External Id should not be mandatory on upsert

- lib/connection.js
- lib/oauth2.js
In order to support public client,
- make client secret to optional in token request
- add code challenge params in authorization request / code verifier params in token request
> Accept code challenge and verifier in requesting authorization and request token

- lib/connection.js
As the refresh flow does not always need the oauth2 client secret in former enhancement (#735), it should be removed to work the refresh flow completely.
> Remove client secret check to accept refresh token

- lib/cli/cli.js
- package.json
Fixes: https://github.com/jsforce/jsforce/issues/751, https://nodesecurity.io/advisories/663
`open` appears to have a command injection vulnerability. This is causing any project with `jsforce` as a dependency to fail the node security platform check https://github.com/nodesecurity/nsp. 
The fix is to use `opn`.  Luckily the API is the same, so very little to change.
> replace deprecated `open` with `opn`

- lib/record-stream.js
As described in this [issue](https://github.com/jsforce/jsforce/issues/764) errors during csv parsing are uncatchable by the client. Apologies for not writing a unit test for this but I'm not sure it would be possible  using the salesforce developer account and I didn't want to introduce a mocking framework to your codebase.
> Catch csv parsing errors and emit

- lib/connection.js
- lib/sobject.js
- test/connection-crud-many.test.js
- test/package/JSforceTestSuite/permissionsets/JSforceTestPowerUser.permissionset
When `create` or `update` are called with many records, these are broken down into individual requests. Therefore there are a lot of requests in flight at once. This has caused issues for us including delays and `UNABLE_TO_LOCK_ROW` errors.
In some places in our app, we have used the Bulk API instead, but this is not ideal where an interactive/immediate response is expected. It can lead to timeouts where an error is returned to our app, but the bulk action eventually goes ahead successfully.
The [Composite Resources](https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/resources_composite.htm), specifically the "SObject Tree" or "SObject Collections", sound like a good solution to this, as we get to submit a number of records at once and get a quick response.
I have …
> Add additional CRUD functions using "composite resources", to better handle writes to a "medium" number of records

- lib/connection.js
- lib/query.js
- lib/sobject.js
- test/bulk.test.js
- test/query.test.js
As far as the queried record num is not so big as the given threshold, use collection API instead of bulk API, which is a little heavy and has always delay of polling.
The threshold value can be modified by passing options.
> Use SObject collection API for query update/destroy operation

- lib/cli/cli.js
- package.json
As JSforce supports OAuth2 PKCE and client secret information is not necessary for public client, the CLI (REPL) does not require any client secret information.
So we put the default OAuth2 client information on the public URL with its client id and redirect URL, and if the CLI cannot find the client information it will automatically download the info and register as the default.
As a result, new connected app registration is not required for JSforce CLI users.
> Allow auto client registration for default

- lib/api/streaming.js
- lib/core.js
- lib/streaming-extension.js
First of all, thank you @stomita for creating & sharing this amazing library 🙏 🙇 😊 
I've been working on a few projects internally at Salesforce that use the jsforce Streaming API to subscribe to **[Platform Events](https://developer.salesforce.com/docs/atlas.en-us.212.0.platform_events.meta/platform_events/platform_events_intro.htm)** (GA/released) and **[Change Data Capture](https://releasenotes.docs.salesforce.com/en-us/spring18/release-notes/rn_data_change_events.htm?edition=&impact=)** (pilot) streams.
🔺 **Breaking changes to this PR as of 2018-07-17.** If you're tracking this branch to use these features, please update your client code to use the newest API:
* `conn.streaming.createClient()` is now the only way to construct a new Faye client with extensions; `withExtensions()` has …
> Streaming API extensions, replay extension, & auth failure detection

- package-lock.json
- package.json
mocha 2 has dependency with growl 1.9.2, which has known vurnability.
upgrade to the latest.
> Update mocha and its depending growl with vurnable version

- lib/connection.js
Now `new Buffer()` is  deprecated.
[buffer](https://nodejs.org/api/buffer.html#buffer_new_buffer_array)
> Stability: 0 - Deprecated: Use Buffer.from(array) instead.
> FIX new Buffer()

- lib/api/metadata.js
Metadata.checkDeployStatus response parameter **runTestsEnabled** does not match other response parameter types. **runTestsEnabled** is returned as a string type, whereas other parameters are returned as boolean type.
Example:
```   
console.log('Checking status for Deploy Request: ' + id);
let conn = new jsforce.Connection({
instanceUrl: oauth2.instanceUrl,
accessToken: oauth2.accessToken,
});
return await conn.metadata.checkDeployStatus(id, true);
```
> Update checkDeployStatus response parameter "runTestsEnabled"

- lib/api/streaming-extension.js
This PR adds an extra check to prevent the final extension in the pipeline from overwriting the Replay ID Mapping when it is not a subscription for the relevant channel.
This is a proposed fix for #814.
> Fix multiple Replay extensions' interference

- lib/record-stream.js
When emitting an error due to a bad CSV parsing, the event would recur itself which will ultimately cause a `RangeError: Maximum call stack size exceeded` error. This fix that issue.
Original PR was https://github.com/jsforce/jsforce/pull/775. It was working fine at the time because of the arrow function.
> Fix recursive error bug

- lib/connection.js
Resolves issue #813
Issue subject: REST API - upsert on collections with { allOrNone: false } does not return array of errors
> resolve issue #813 - bug in upsert of Collections

- lib/csv.js
- package-lock.json
- package.json
When updated the `csv-parse` to 4.6.3, it raises the error while building browser build as it contains non-es5 statement. Change to explicitly use the es5 code by requiring the lib in proper path.
> Change to use es5 version of csv-parse

- package-lock.json
- package.json
This addresses the security issue reported by NPM and discussed in #925.
It does not appear that JSForce itself needs to change, however in theory this could be a breaking change for downstream projects since it is a change in major version of csv-parse and calls passing through may be impacted if they are using deprecated calls.
[csv-parse changelog](https://csv.js.org/parse/changelog/) Obviously reports lots of changes since that time including dropping support for old versions of Node, move to the MIT license, and more aggressive skipping of empty records.
> Bump csv-parse to 4.6.3

- lib/api/chatter.js
- test/chatter.test.js
Changes:
- Fix typo on update param type annotation on chatter API
- Replace POST method by PATCH for update function on chatter API
- Add missing small test for update function
Issue reference: https://github.com/jsforce/jsforce/issues/944
> Fix hardcoded http method chatter api

- lib/api/apex.js
Fixes issue #946 by not automatically serializing Apex REST request body into JSON.
Body will be serialized in JSON if either:
- no content type is set
- content type is `application/json`
> Allow non JSON content type in Apex REST

- api/apex/package.json
- index.js
- src/api/apex.ts
- src/connection.ts
- src/core.ts
- src/index.ts
- src/jsforce.ts
- src/registry/base.ts
- src/registry/sfdx.ts
- src/registry/types.ts
Currently `Connection` class imported from 'jsforce' has api lib modules reference in its properties, on the other hand that from 'jsforce/core' doesn't. It is to remove unnecessary reference to reduce the bundled code size. Unify the interface to have the api module properties, but actual access in connection from 'jsforce/core' to become error.
> Unify connection interface loaded from 'jsforce' and 'jsforce/core'

- build/jsforce-api-metadata.js
- build/jsforce-core.js
- build/jsforce.js
- lib/api/metadata.js
Still `new Buffer()` deprecated error.
[Buffer](https://nodejs.org/api/buffer.html#buffer_new_buffer_array)
> Stability: 0 - Deprecated: Use Buffer.from(array) instead.
> fix: buffer compatibility with node 10

- package-lock.json
- package.json
- src/VERSION.ts
- src/csv.ts
As the csv-parse/stringify includes non-es5 syntax, it fails when bundled and run in classic web browser like IE11.
> Use es5 built file for csv-parse/stringify usage

- lib/soql-builder.js
- test/soql-builder.test.js
Support multiple conditions in a single field, as in `{ "Date": {  "$gte": "2020-02-24", "$lt": "2020-02-25" } }`.
> fix: support multiple conditions per field

- package.json
Shinichi, can you please verify and merge this request. In our latest scan package 'CSV-PARSE' marked as high vulnerability in jsforce module.
> Version update from 4.6.3 to 4.10.1 to address vulnerabilities

- package-lock.json
- package.json
Update lodash to 4.17.19 to fix Object Prototype Pollution Security Vulnerability:
* Snyk lodash vulnerability report https://snyk.io/vuln/SNYK-JS-LODASH-567746
* Merged/released lodash PR: https://github.com/lodash/lodash/pull/4759
> Update lodash to 4.17.19 to fix Object Prototype Pollution Security Vulnerability

- .gitignore
- package.json
This PR removes the `test` folder from getting published to `npm`. 
It also updates the `.gitignore` file, adding some missing files/folders that should be ignored.
> fix: update gitignore & remove test folder from getting published to npm

- src/api/bulk.ts
- src/api/streaming.ts
- src/cache.ts
- src/connection.ts
- src/http-api.ts
- src/jsforce.ts
- src/query.ts
- src/request.ts
This fix is really essential since `Connection`  class is now missing `on`, `off`, etc. functions inherited from the EventEmitter namespace.
This happened in other libraries as well (e.g. [https://github.com/geckosio/geckos.io/issues/22](https://github.com/geckosio/geckos.io/issues/22)).
I hope this could be merged quickly.
Thanks
> Fix eventemitter

- index.d.ts
- package.json
Module `faye` has no type definition so the jsforce has its own custom type definition in `typings/faye`, but the packaged npm lib will not resolve unless the developer specifies the typesRoot path in compiler config. Include the reference in the entry file to force it to load.
> Fix  custom type definition resolution for faye

- core/index.d.ts
- core/package.json
- index.d.ts
- package-lock.json
- package.json
- typings/index.d.ts
When the lib user project has setting of `tsconfig.json` with `skipLibCheck` = false, it raises error like 
```
node_modules/jsforce/lib/api/bulk.d.ts:6:30 - error TS2307: Cannot find module 'events' or its corresponding type declarations.
6 import { EventEmitter } from 'events';
~~~~~~~~
node_modules/jsforce/lib/api/bulk.d.ts:7:44 - error TS2307: Cannot find module 'stream' or its corresponding type declarations.
7 import { Duplex, Readable, Writable } from 'stream';
~~~~~~~~
```
This PR fixes it by including the type definition lib `@types/node` to`dependencies`, instead of `devDependencies`.
Additionally, it also fixes the private type definitions in `./typings` will not be loaded when the lib is imported from `jsforce/core`, not from 'jsforce'.
> Fix unresolved type definition resolutions

- src/connection.ts
Fix missing URL error in Visualforce in experience cloud, which requires sub directory path in instance URL, like `/portal` or `/community`.
> Skip prefixing instance URL if it is already prefixed

- package-lock.json
- package.json
Updates `faye` to `^1.4.0` to get latest security fixes
Closes #1195
> chore: bump faye to 1.4.0

- src/transport.ts
sfdx issue with repro: https://github.com/forcedotcom/cli/issues/1626
closes https://github.com/jsforce/jsforce/issues/626
NOTE: this does not provide support for both HTTPS and HTTP proxies simultaneously.  Code in jsforce is using HTTPS
https://github.com/jsforce/jsforce/blob/90a5423c43da3758bdcefb32b17aaa1dc09828a9/src/request.ts#L38
but grabs the env named `HTTP_PROXY`
https://github.com/jsforce/jsforce/blob/90a5423c43da3758bdcefb32b17aaa1dc09828a9/src/transport.ts#L24
this lets you use either, with a preference for `HTTPS_PROXY`
@[W-11426296](https://gus.lightning.force.com/a07EE000011OdYaYAK)@
> fix: support HTTPS proxy env

- .github/workflows/manualRelease.yml
- .github/workflows/onRelease.yml
- scripts/build.js
Add a GHA workflow to do releases from CI via a manual trigger.
It has a few specific values like `pre-release-identifier` that should be deleted once v2 is GA.
The test pipeline still runs on Circle and doesn't have any integration with this, so once you merge a PR you need to manually trigger a release from the actions tab.
**TODO**:
1) add npm and GH tokens
>  chore(ci): add manual release workflow

- src/types/common.ts
In jsforce@v2.0, defined DescribeGlobalSObjectResult type in [src/types/common.ts](https://github.com/jsforce/jsforce/blob/74d4dd37f385f2ae1ab3af1747793afb853755d1/src/types/common.ts#L212) doesn't have idEnabled property while it is defined in [src/api/soap/schema.ts](https://github.com/jsforce/jsforce/blob/74d4dd37f385f2ae1ab3af1747793afb853755d1/src/api/soap/schema.ts#L605), which is causing type error in Typescript.
> [v2.0] Add missing type prop not matching with api/soap/schema.ts 

- .github/workflows/manualRelease.yml
Added a new collaborator `svc-cli-bot-jsforce` that created a token that will **only** have access to jsforce/jsforce. Updated the token name here to make this distinction clear
> Updates token name

- src/api/analytics.ts
- src/core.ts
- src/registry/index.ts
add type to type only imports and exports
This is to play nice with bundlers.
babel removes the type info from the types files since js does not care about them.
This has the effect of having an import with no export which bundlers do not like.
You can see this most clearly in the analysis.ts file which 
is re exporting types from the types file.
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html#type-only-imports-and-export
resolves #1342
> chore: fix types for bundling

- src/connection.ts
- src/core.ts
- src/jwtOAuth2.ts
As the latest update of jsforce (beta25), which includes removal of JwtOAuth2 #1341 , `sfdx-cli` is failing for the absence of `jsforce_1.JwtOAuth2`. This will be fixed in the `sfdx-core`, but the fix is not yet merged and it requires all sfdx-cli users to update its version because the sfdx-core is depending jsforce in caret versioning (^2.0.0-beta.24), which automatically select the latest beta version.
Considering the impact of this disfunction, I would like to bring back the JwtOAuth2 module, but with deprecated warning.
> Bring back JWT OAuth2 module (as deprecated)

- .github/workflows/publishDocs.yml
Adds empty workflow to `master` to test the publish-docs workflow.
> ci: add empty publish-docs workflow

- jest.setup.js
- package-lock.json
- package.json
- src/http-api.ts
- src/soap.ts
- src/util/get-body-size.ts
- test/body-size.test.ts
feat: automatically set `content-length` header on REST/SOAP requests.
We've been getting a few reports that some internal envs started to enforce this header on requests, adding support in jsforce as a safety measure.
while working on this I found the HTTP module doesn't any UT, there's some coverage for session refresh in different e2e tests but we today we don't have an easy way to test this behavior, I'll add some tests for this when working on
[W-14580746: [jsforce]: increase HTTP module test coverage]
(https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001fXgwbYAC/view)
not really an easy way to QA this without getting one of those internal envs, but you can try running tests with this env var:
`JSFORCE_LOG_LEVEL=DEBUG` to get the body size added in each request (I tried …
> feat: set content-length header

- karma.conf.js
- package-lock.json
- package.json
- scripts/org-setup.mjs
- src/http-api.ts
- test/bulk2.test.ts
- test/helper/webauth/index.ts
- test/http-api.test.ts
- test/streaming.test.ts
Adds unit tests for the HTTP API module (including SOAP wrapper).
UTs cover HTTP/SOAP headers, session refresh, parsing error in responses.
@W-14580746@
> test: add tests for HTTP API module

- src/request-helper.ts
- src/request.ts
- src/types/common.ts
- test/http-api.test.ts
This PR adds a simple retry mechanism for the node-fetch wrapper.
Implements some options of undici's (node's fetch) retry handler:
https://undici.nodejs.org/#/docs/api/RetryAgent
jsforce v4 will target native fetch on node/browser so the retry API will stay the same for node consumers.
1. this code will very likely get removed in jsforce v4 (node's fetch handles retries)
2. the retry mechanism is at the low-level request helper and relies on node-fetch actually throwing, 
Connection class is instantiated, it sets the HTTP transport:
https://github.com/jsforce/jsforce/blob/3a88038617494cd2c877f152363218f17939c400/src/connection.ts#L346-L350
then `HttpApi.httpRequest` gets the `request` wrapper here:
https://github.com/jsforce/jsforce/blob/3a88038617494cd2c877f152363218f17939c400/src/transp …
> feat: retry on network errors

- src/request.ts
- src/types/common.ts
- test/http-api.test.ts
feat:
1. adds support for retry on status codes
2. adds support for minTimeout/timeoutFactor, this makes each retry to be delayed incrementally.
couldn't find a way to reliable UT n2 but this should mimic undici's behavior.
1) install sf >= 2.38.3 (that uses jsforce-node)
2) checkout this PR and build jsforce-node:
a. `npm install` install 
b. `npm run jsforce-node` build jsforce-node (you'll see pjson changes, don't revert them)
c. link it into sfdx-core
3) compare time between retries:
turn off your wifi and try this with no plugins linked, you will see the retries happen instantly:
```
JSFORCE_LOG_LEVEL=DEBUG sf org list 
```
then run the same command on plugin-org, see each retry waits a bit longer:
```
JSFORCE_LOG_LEVEL=DEBUG ./bin/dev.js org list
```
@W-15451832@
> feat: retry on statusCodes

- .github/workflows/externalNut.yml
- scripts/org-setup.mjs
Updates external NUTs workflow to use jsforce-node instead of jsforce when linking it into sf plugins.
Also fixes org-setup script failing on node v22 (see the failure in the first commit, node-latest run).
> ci: external NUTs use jsforce-node

- .github/workflows/tests.yml
- package.json
- scripts/org-setup.mjs
- src/api/bulk2.ts
- test/bulk.test.ts
- test/bulk2.test.ts
Enable e2e tests on Windows, updated the org-setup script to fix some path issues that where blocking this.
After getting these running I was getting this failure even after setting the correct lineEnding value for windows:
https://github.com/jsforce/jsforce/actions/runs/8818324210/job/24206906041#step:8:645
turns out `bulk2.loadAndWaitForResults` wasn't passing job bodyParams down when creating the job, fixed in this commit:
https://github.com/jsforce/jsforce/commit/8e63fd024c8afe6cf6c2f721072727b91c94aee9
@W-13879927@
> test: run e2e tests on windows

- MIGRATING_V1-V3.md
- MIGRATING_V2-V3.md
Adds migration guide for jsforce v1 -> v3 and v2 -> v3.
Added a few speciifc examples but otherwise redirect to jsforce.github.io which will include the new examples after merging this PR: https://github.com/jsforce/jsforce-website/pull/23
@W-15692725@
> docs: add migration guides

- package-lock.json
- src/connection.ts
- test/connection-session.test.ts
@W-15748051@
https://github.com/jsforce/jsforce/issues/1352
validates instanceUrls as non lightning before creating connections with them
> fix: throw error if lightning url passed as instance url

- .github/workflows/manualRelease.yml
- .github/workflows/publishDocs.yml
- README.md
- test/connection-session.test.ts
Updates typedoc workflow to push site build to `gh-pages`.
I pushed the first build from local to confirm it Jekyll build worked while retaining the v1 API ref at `doc`:
https://github.com/jsforce/jsforce/tree/gh-pages
Changed GH pages it to serve from the root:
v3: https://jsforce.github.io/jsforce/
v1: https://jsforce.github.io/jsforce/doc/
When users click on `API Reference` in https://jsforce.github.io/ they will get to the v3 API ref. The main page is the readme which links to v1 ones.
changed here: https://github.com/jsforce/jsforce.github.io/commit/63913c07f95cd2cd6f0a4a57ff8922f81a974bf7
@W-15807592@
> docs: set up v3 API ref. site

- src/api/bulk.ts
- test/bulk.test.ts
adds missing field to batch results records.
ref https://github.com/jsforce/jsforce/issues/796
Bulk V2 already includes it:
https://github.com/jsforce/jsforce/blob/af8a10e84557d95e20a62dae37e9dbf1e4d50fa8/src/api/bulk2.ts#L71
> fix(bulk): add missing `created` field

- src/api/bulk.ts
ref https://github.com/jsforce/jsforce/issues/765
Possible bulk job states:
https://developer.salesforce.com/docs/atlas.en-us.api_asynch.meta/api_asynch/asynch_api_batches_interpret_status.htm
Bulk V2 module already does handles this scenario:
https://github.com/jsforce/jsforce/blob/b661afdd21729812974f1056e392f2f58fc21096/src/api/bulk2.ts#L486
> fix(bulk): stop polling if job was aborted

- src/connection.ts
- test/connection-session.test.ts
- test/http-api.test.ts
fixes:
* https://github.com/jsforce/jsforce/issues/1308
* https://github.com/jsforce/jsforce/issues/1411
Fix bug where trying to `conn.login` with an expired password would cause an infinite loop.
`conn.login` sets a refresh delegate function:
https://github.com/jsforce/jsforce/blob/2621d0b863487056ce25f949ad8d007125ed04b7/src/connection.ts#L507
the func calls `conn.login` and grabs `conn.accessToken`:
https://github.com/jsforce/jsforce/blob/2621d0b863487056ce25f949ad8d007125ed04b7/src/connection.ts#L185
the API returns 200 with `passwordExpired` set to `true` and a restricted access token (you can use it only to set a new password via `setPassword`):
https://developer.salesforce.com/docs/atlas.en-us.api.meta/api/sforce_api_calls_login_loginresult.htm
so any subsequent request would …
> fix(login): throw if password expired

- src/session-refresh-delegate.ts
- test/connection-session.test.ts
Any failure coming from `refreshFn` should surface as a session-refresh failure.
Example throwing in `refreshFn`:
> fix(session-refresh): improve error message

- .github/workflows/create-github-release.yml
- .github/workflows/onRelease.yml
- README.md
- package.json
Prepare for GA:
* updates release workflows to publish v3 as `latest`
* rename `manualRelease.yml`, will now run on push to `main`
> chore: update workflows

- src/oauth2.ts
- test/oauth2.test.ts
we got a report from devs running local Salesforce builds that the double-slash in the oauth URL is no longer working (prod has been parsing it successfully for now). This PR updates the oauth class in jsforce to always return a valid URL without the double-slash even if the provided loginURL has it.
repro:
run `sf org login web -a devhub --dev-debug -r https://localhost:6101` (don't need access to an internal org, just check the URL opened), should get the same as in the screenshot above ⬆️ 
1. checkout this PR and link it into plugin-auth: 
```
npm i && npm run build:node:cjs && npm run jsforce-node:dev
```
2. in plugin-auth, run: `./bin/dev.js  org login web -a devhub -r https://localhost:6101`, you should see the oauth URL without the double-slash:
@ W-16215453@
> fix(oauth2): ensure endpoints are valid

- src/registry/index.ts
I found Error log in CloudWatch Logs  because of `cosole.error`.
https://github.com/jsforce/jsforce/issues/979#issuecomment-2231952572
> fix: use logger instead of `console.error`

- src/api/bulk2.ts
@W-16325607@
https://github.com/forcedotcom/cli/issues/2968
removes a `//` from URLs when getting query results, not sure if this will fix the issue. I was never able to reproduce it, but saw this in the logs
`query//750Hn00000OUfXPIA1/results?locator=MDowR2`
now 
`query/750Hn00000OUfXPIA1/results?locator=MDowR2`
> fix: try removing // from URl

- src/connection.ts
Fix provides ability to set type of Record returned from `queryMore()` method. This is same functionality as `query()`.
> Adding ability to provide type of record for Connection.queryMore method

- package-lock.json
- package.json
- src/registry/sfdx.ts
This pull request replaces `strip-ansi` with [`util.stripVTControlCharacters`](https://nodejs.org/api/util.html#utilstripvtcontrolcharactersstr) native API available since Node 16.11.
This change will reduce the amount of dependencies installed by 1
> chore(deps): replace strip-ansi with native Node API

- src/api/bulk2.ts
Allow to fetch raw CSV results from bulk2 jobs.
The getResults method would fetch the CSV, parse them into JS arrays and cache that in an internal class field, this PR adds support for these methods to return results a CSV (string) and intentionally skip caching to avoid switching types.
Required for:
https://github.com/salesforcecli/plugin-data/pull/1097
@W-12408034@
> feat(bulk2): allow to get raw job results

- src/oauth2.ts
- test/oauth2.test.ts
Allow the OAuth2 module to handle supported URLs:
> All OAuth endpoints require secure HTTP (HTTPS). For standard OAuth 2.0 authorization flows, these host domains are supported unless otherwise specified.
login.salesforce.com
A My Domain URL, such as https://MyCompany.my.salesforce.com
An Experience Cloud site URL, such as https://MyDomainName.my.site.com
A custom URL
For sandboxes, use test.salesforce.com or the My Domain login URL for the sandbox, such as MyDomainName--SandboxName.sandbox.my.salesforce.com.
https://help.salesforce.com/s/articleView?id=sf.remoteaccess_oauth_endpoints.htm&type=5
A community URL like `https://innovation-momentum-8840-dev-ed.scratch.my.salesforce.com/AppCentral` would get the pathname (`/AppCentral`) trimmed.
URL pathname is kept, jsforce handles possible …
> fix(oauth2): don't strip URL path

- src/csv.ts
- test/bulk2.test.ts
- test/data/Account_bulk2_test_backquote.csv
Add known CSV delimiters to the CSV parse helper used to parse a request body.
csv-parse:
https://csv.js.org/parse/options/delimiter/
for `sf data upsert/delete bulk` we call `job.getAllResults()` expecting the CSV result records as JS values but if a user uploaded a CSV file using a delimiter other than `COMMA` then the CSV parser here would fail and we get back the CSV as a string:
https://github.com/jsforce/jsforce/blob/0bbf6313628ff5380138ea5df23b06a59d4fe58c/src/http-api.ts#L220
https://github.com/salesforcecli/plugin-data/pull/1110
@W-16971607@
> fix(http): handle more CSV delimiters on parse

- src/http-api.ts
Temporal fix to make jsforce exit early on Agent API requests where the agent being queried doesn't have a connected app linked and keeps returning `401` (infinite session-refresh loop).
Example response from curl:
```
{"status":401,"path":"v6.0.0/agents/<id>/sessions","mode":"unknown","requestId":"3c982dec-4502-4d4c-9efb-ea1bb1b601b0","error":"UnauthorizedException","message":"Connected app is not attached to Agent","timestamp":1740073984584,"expected":false}
```
testing:
checkout locally and build jsforce-node, see:
https://github.com/jsforce/jsforce/blob/main/DEVELOPING.md#getting-started
then link it into sfdx-core
@W-17875499@
> fix: skip session refresh on bad Agent API reqs W-17875499

- src/request.ts
- test/http-api.test.ts
Fixes: https://github.com/jsforce/jsforce/issues/1642
Removes the bad `RequestRetryError` error (sorry about it, can't remember why I added it tbh).
If a request still fails and reaches the max retry limit we now return the response (or node-fetch error) instead of the generic error.
Example on with `sf` on agent test API returning 500:
```
➜  plugin-agent git:(main) sf api request rest services/data/v63.0/einstein/ai-evaluations/runs/4KBed000000b3erGAA
Warning: This command is currently in beta. Any aspect of this command can change without advanced notice. Don't use beta commands in your scripts.
[
{
"errorCode": "INTERNAL_SERVER_ERROR",
"message": "Invalid AiEvaluation identifier"
}
]
```
```
➜  plugin-agent git:(main) ./bin/run.js agent test resume --job-id 4KBed000000b3erGAA
Warning: …
```
> fix(http): return res/err after retry is done W-17919119

- src/api/metadata.ts
- test/metadata.test.ts
`metadata.checkDeployStatus()` now supports an optional `rest` param to call the deploy status REST endpoint rather than always using SOAP.  SOAP is still the default if the `rest` param is not passed.  Added a test for this code path as well.
@W-18012955@
> feat: add checkDeployStatus for REST W-18012955

- src/query.ts
- test/sobject.test.ts
Fixes: https://github.com/jsforce/jsforce/issues/1676
When doing `sobject().find().update()`, jsforce evaluates the update fields for possible record templates (jsforce syntax sugar for easy string replacement), for the mentioned use-case in #1676 we now allow to skip it via a new boolean option.
Tests added by Cursor 🪄 (needed some polish but were almost perfect).
@W-18268091@
> feat: allow skipping template eval on query update W-18268091

- .github/workflows/tests.yml
- package-lock.json
- package.json
Bumps most babel deps/devDeps to latest (non-major bumps).
Ref: https://github.com/jsforce/jsforce/issues/1681
Other: 
bumps wireit dep and CI cache action, that was blocking some dependabot PRs:
https://github.com/jsforce/jsforce/pull/1680
> fix: bump babel deps

- test/org-setup/project-scratch-def.json
This small patch adds the `language` attribute to the scratch org's definition file so that developers that wish to contribute to the project all work on the same language for the org. 
Reason: some unit tests require an exact match to messages provided by the platform's API in English.
> feat: adds language attribute to the scratch org's definition file

- src/soap.ts
- src/util/jwt.ts
- test/jwt-util.test.ts
Update the SOAP module to throw if the provided `connection` is using a JWT-based access tokens.
Due to how session-refresh works and SOAP APIs not support JWT tokens, trying to use them makes jsforce enter into an infinite loop trying to fetch a valid token.
1. checkout this PR and build jsforce-node: `npm i && npm run jsforce-node:dev && npm run build:node:cjs`
2. link it into plugin-deploy-retrieve or plugin-org: `yarn link @jsforce/jsforce-node`
3. auth to an org using a connected app with JWT-access tokens enabled.
4. run a command that does a SOAP request like `project deploy start`/`org list metadata`:
without this PR, jsforce enters the infinite loop (set `JSFORCE_LOG_LEVEL=DEBUG` to debug logs).
Now any code trying to do SOAP requests will fail like this:
@W-18585436@
> fix(SOAP): block connections using JWT tokens W-18585436

- package-lock.json
- src/http-api.ts
don't set content-length in browser.  The browser automatically does it and trying to mess with it violates browser security rules.
request.ts:180 Refused to set unsafe header "content-length"
eval	@	request.ts:180
_callee2$	@	request-helper.ts:103
executeWithTimeout	@	request-helper.ts:88
_callee4$	@	request.ts:175
Promise.then		
startXmlHttpRequest	@	request.ts:162
request	@	request.ts:271
eval	@	transport.ts:51
create	@	promise.ts:24
httpRequest	@	transport.ts:49
_callee$	@	http-api.ts:98
eval	@	http-api.ts:157
create	@	promise.ts:24
request	@	http-api.ts:65
_callee$	@	soap.ts:231
invoke	@	soap.ts:225
_callee$	@	metadata.ts:116
_invoke	@	metadata.ts:107
describe	@	metadata.ts:283
> W-19055021 fix: no setting content-length in browser

- package-lock.json
- src/request.ts
- test/http-api.test.ts
Adds a default timeout (60 seconds) in the node-fetch wrapper to prevent hanging requests.
node-fetch v2 default is `0`:
https://github.com/node-fetch/node-fetch/tree/2.x?tab=readme-ov-file#options
We have a customer that is able to start a metadata retrieve via `sf project retrieve start` and get a few retrieve status checks SOAP calls done but then hangs at `calling metadata.checkRetrieveStatus` for 33 minutes (CLI default wait time)
```
[12:52:40.164] DEBUG (sf:MetadataApiRetrieve): MDAPI status update: InProgress
[12:52:40.665] DEBUG (sf:MetadataApiRetrieve): getting connection instance
[12:52:40.665] DEBUG (sf:MetadataApiRetrieve): calling metadata.checkRetrieveStatus
[12:52:40.734] DEBUG (sf:MetadataApiRetrieve): successfully called metadata.checkRetrieveStatus
[12:52:40.734] DEBUG …
```
> fix: set default request timeout W-18649787
