- package.json
- test/analytics.test.js
- test/apex.test.js
- test/bin/run-test
- test/bulk.test.js
- test/chatter.test.js
- test/connection-crud.test.js
- test/connection-meta.test.js
- test/helper/browser/test-utils.js
- test/helper/node/test-utils.js
- test/helper/test-utils.js
- test/metadata.test.js
- test/query.test.js
- test/sobject.test.js
- test/streaming.test.js
- test/tooling.test.js
Enhance mocha test runner to accept .env file for local testing, and add session management not to override the test data in testing org.
> Enhance CI test stability

- lib/api/bulk.js
- lib/api/metadata.js
- lib/http-api.js
- lib/soap.js
- test/bulk.test.js
- test/helper/async-check.js
- test/metadata.test.js
Enable session refresh using refresh token (or other refresh scheme) in metadata api call
> Enable metadata api session refresh

- .travis.yml
- lib/connection.js
- lib/http-api.js
- lib/soap.js
- test/connection-meta.test.js
Attach call option header both in rest and soap api
> Add call option support

- lib/api/analytics.js
- lib/api/apex.js
- lib/api/chatter.js
- lib/api/tooling.js
- lib/connection.js
- lib/query.js
- lib/record.js
- lib/sobject.js
Make interface public to request generic REST api endpoint
> Open generic REST API request interface

- lib/cli/cli.js
- lib/cli/repl.js
Add '.open' command in JSforce REPL to access web page using established connection.
> Support "open" command in REPL

- lib/query.js
Add support of explaining plan of query execution
> Support exaplain plan in query

- lib/connection.js
- lib/process.js
- test/helper/async-check.js
- test/process.test.js
https://developer.salesforce.com/docs/atlas.en-us.192.0.api_rest.meta/api_rest/resources_process_rules.htm
https://developer.salesforce.com/docs/atlas.en-us.192.0.api_rest.meta/api_rest/resources_process_approvals.htm
> Process Rules/Approvals REST API endpoint support

- lib/sobject.js
- test/sobject.test.js
https://developer.salesforce.com/docs/atlas.en-us.192.0.api_rest.meta/api_rest/resources_sobject_compactlayouts.htm
> SObject CompactLayouts REST API endpoint support

- lib/sobject.js
- test/sobject.test.js
https://developer.salesforce.com/docs/atlas.en-us.192.0.api_rest.meta/api_rest/resources_sobject_layouts.htm
> SObject layouts REST API endpoint support

- lib/sobject.js
- test/sobject.test.js
https://developer.salesforce.com/docs/atlas.en-us.192.0.api_rest.meta/api_rest/resources_sobject_named_layouts.htm
> SObejct NamedLayout REST API endpoint support

- README.md
Fix typo, grammatical errors, run-on sentences.
> Typo gramatical errors

- lib/sobject.js
- test/sobject.test.js
https://developer.salesforce.com/docs/atlas.en-us.192.0.api_rest.meta/api_rest/resources_sobject_approvallayouts.htm
> SObject ApprovalLayouts REST API endpoint support

- lib/connection.js
- lib/quick-action.js
- lib/sobject.js
- test/quick-action.test.js
https://developer.salesforce.com/docs/atlas.en-us.192.0.api_rest.meta/api_rest/resources_quickactions.htm
https://developer.salesforce.com/docs/atlas.en-us.192.0.api_rest.meta/api_rest/resources_sobject_quickactions.htm
> QuickActions REST API endpoint support

- lib/connection.js
Change default API version to 33.0 (Spring '15)
> Change default api ver to 33.0

- .travis.yml
Enable npm module caches, run on container
> Refine travisCI setting

- lib/api/bulk.js
- lib/api/tooling.js
- lib/connection.js
- lib/jsforce.js
- lib/promise.js
- lib/query.js
- package.json
- test/helper/node/webauth.js
Change current promise implementation ('q') to lightweight one ('promise')
> Change Promise implementation

- lib/api/streaming.js
- test/streaming.test.js
https://developer.salesforce.com/docs/atlas.en-us.194.0.api_streaming.meta/api_streaming/generic_streaming_intro.htm
> Generic Streaming Support

- lib/api/analytics.js
- lib/sobject.js
- test/analytics.test.js
- test/sobject.test.js
In Spring '15, explain plan supports not only query, but also report and listview.
> Support explain execution plan in report and list view

- test/connection-meta.test.js
- test/helper/testenv.js
- test/helper/user-pool.js
Continued from #244
Add retrying to get user account from user pool
> Refine testing environment (cont.)

- lib/api/metadata.js
- test/bulk.test.js
- test/helper/testenv.js
Fix for #241 .
Change to use data event for deploying metadata zipfile.
> Fix error in deploying metadata on Node 0.12

- Gruntfile.js
- lib/jsforce.js
- package.json
To reference version information, add VERSION property in jsforce object
> Add version info in jsforce object root

- lib/http-api.js
probable fix for https://github.com/jsforce/jsforce/issues/196
> update request url if instance url has changed after a token refresh

- test/helper/node/webauth.js
- test/metadata.test.js
As new login UI is introduced, several tests which use webdriver to automatically login to the instance fails.
> Fix webdriver login to keep up with new login UI

- test/helper/node/webauth.js
- test/metadata.test.js
Metadata rename operation fails in metadata.test.js.
> Fix metadata rename error in test

- lib/promise.js
> Remove Promise#done() in jsdoc

- .travis.yml
- package.json
Remove official support of node.js 0.10.x in package.json and TravisCI test target.
> Remove support of Node.js ver 0.10.x

- lib/api/apex.js
- package.json
> Added support for custom headers

- lib/api/metadata.js
> Fix jsdoc of Metadata#upsert and add jsdoc of Metadata#upsertSync

- lib/api/tooling.js
> Add Run Tests Synchronous Tooling

- lib/api/bulk.js
- package.json
I've done some basic testing on my end and am now using this via a fork for my project. Solves #429.
> fix: combine all batches from bulk api into single stream

- package.json
- test/bin/run-test
- fix warning of .env file is not found
- fix warning of through2 package is duplicated in devDependencies
> Fix warnings/errors in ci execution

- gulpfile.babel.js
- lib/dynreq/require.js
- lib/require.js
- package.json
Add support webpack bundling to 1.6 based code
> Add support webpack bundling

- lib/VERSION.js
- lib/core.js
- package.json
Add VERSION file to load the current version info.
Also added prepublish script which ensures the package.json's version is equal to the VERSION file.
From #479
> Remove package.json reference

- gulpfile.babel.js
- lib/_required.js
- lib/api/bulk.js
- lib/csv.js
- lib/record-stream.js
- package.json
- test/bulk.test.js
> Use stream CSV parser library while handling bulkquery result CSV

- lib/api/streaming.js
- lib/connection.js
As Summer'16 is released, changing default API ver to the latest.
> Change default API ver to 37.0

- lib/query.js
- package.json
> includes subquery behave properly and added sort fixes #11

- lib/connection.js
- lib/sobject.js
> Use headers for requestGet, retrieve, identity, find and describe calls

- README.md
> Document -> Documentation

- lib/soql-builder.js
- test/soql-builder.test.js
> Added INCLUDES and EXCLUDES to the opMap

- lib/query.js
> Check that data.records isn't undefined or null before checking the number of records

- lib/api/analytics.js
If the arguments are all omitted, it should not include it in post body.
> Fix componetnIds argument handling in Dashboard#components() method

- lib/api/soap.js
- test/soap.test.js
Hi,  @stomita 
Could you review this PR please, I've added "CRUD" operation support to the soap api library.
Thanks.
> Add features of Create, Update, Upsert, Delete with SOAP API

- lib/query.js
- lib/sobject.js
adds sort to the query options for `collection[command].apply(collection, args);`
> add sort to the query options

- test/package/JSforceTestSuite/permissionsets/JSforceTestPowerUser.permissionset
> Add missing ViewRoles permission

- lib/VERSION.js
- package.json
Includes security fix of node-open vulnerability. #752
> Release 1.8.5

- lib/api/apex.js
- lib/api/bulk.js
- lib/query.js
JSDoc fixes for issue #718 and issue #744 as well as another mixup I noticed in lib/query.js
> A few documentation fixes

- lib/connection.js
In order to support clients which already set specific API version, check if the connecting API version supports SObject collection or not.
> Ensure version before using sobject collection APIs

- lib/connection.js
- lib/oauth2.js
In Chrome, CORB (Cross-Origin Read Blocking) prevents to load JSONP response from identity url / revoke server
> remove JSONP endpoint as it is not working in modern browsers

- lib/connection.js
> Correct invalid CRUD save error handling function name

- .travis/test.sh
- ava.config.js
- index.js
- package-lock.json
- package.json
- src/connection.js
- src/oauth2.js
- src/query.js
- src/record-stream.js
- src/sobject.js
- test.es6/analytics.test.js
- test.es6/apex.test.js
- test.es6/bulk.test.js
- test.es6/cache.test.js
- test.es6/chatter.test.js
- test.es6/connection-crud.test.js
- test.es6/connection-meta.test.js
- test.es6/connection-session.test.js
- test.es6/helper/node/webauth.js
- test.es6/metadata.test.js
- test.es6/oauth2.test.js
- test.es6/process.test.js
- test.es6/query.test.js
- test.es6/quick-action.test.js
- test.es6/soap.test.js
- test.es6/sobject.test.js
- test.es6/streaming.test.js
- test.es6/tooling.test.js
- test.es6/util/ava/ext.js
As the most of JSforce test requires synchronous execution, use test.serial by default.
> Change ava to use always serial test

- .circleci/config.yml
- README.md
- test/helper/node/webauth.js
- test/metadata.test.js
> Migrate to circleci

- package-lock.json
- src/cli/cli.ts
Fix prompt error and retry flow so that not to quit REPL env after exceeding retry count.
> Fix Password auth flow in CLI

- src/connection.ts
- src/oauth2.ts
- src/sobject.ts
- test/query.test.ts
In order to match array paramaeter patterns first.
> Change order of overload methods type defs

- package-lock.json
- package.json
- src/VERSION.ts
- src/registry/sfdx.ts
The `--json` output may contain ANSI color information, so remove them from JSON.
> Fix to strip ANSI color from the output of Sfdx CLI

- .gitignore
- api/apex/package.json
- api/metadata/package.json
- api/soap/package.json
- babel.config.js
- package-lock.json
- package.json
In order to use bundlers for web browser add "browser" target
> Output target for browser/module/lib

- src/browser/request.ts
> give up on request body streaming

- package.json
Bumps package version to include this fix: https://github.com/jsforce/jsforce/pull/1256
> fix: bump package version

- src/connection.ts
- src/oauth2.ts
> Support grant types other than authorization code

- src/registry/index.ts
> Fix file registry error in module loading

- .github/workflows/manualRelease.yml
- .github/workflows/onRelease.yml
- scripts/build.js
cherry picked from https://github.com/jsforce/jsforce/pull/1338
> chore(ci): add manual release workflow

- .github/workflows/manualRelease.yml
- .github/workflows/onRelease.yml
prevent accidental run of gha publish actions on main
> ci: empty actions on main

- src/jsforce.ts
Additional fix which is missed in #1349
> Bring back JWT OAuth2 module (as deprecated) (cont.)

- src/api/bulk.ts
- src/connection.ts
- src/oauth2.ts
- test/query.test.ts
Adds jsdoc comments in bulk2 module and other small ones.
Also makes query/ingest job polling methods to include an error when emitting `failure`.
> chore: jsdoc stuff

- scripts/org-setup.mjs
- test/bulk2.test.ts
- test/helper/webauth/index.ts
- test/streaming.test.ts
> test(streaming): fix flaky e2e test

- src/request.ts
- test/http-api.test.ts
SDR was retrying these for deploy polling, probably should do everywhere
@W-16119908@
> fix: retry 420

- src/api/metadata.ts
@W-10908987@
adds a `cancelDeploy` method to be used in SDR
> fix: add cancelDeploy method to metadata

- .github/workflows/tests.yml
- package-lock.json
- src/api/bulk2.ts
Makes ingest/query poll `jobComplete` event include job info
> fix(bulk2): `jobComplete` event includes job info

- package.json
> Set correct entrypoint to module in package.json

- src/soap.ts
- test/metadata.test.ts
> Fix serialization of null property in soap request

- src/connection.ts
References jsforce/jsforce#1691
Update upsert to use the sobject collection when appropriate.  
- API Version must be 46 or later
- Honor the `allowRecursive` and `MAX_DML_COUNT`
- The records argument must be an array otherwise fall back to the original method.
> feat(connection): Update upsert to use sobject collection 

- src/http-api.ts
- src/soap.ts
same as https://github.com/jsforce/jsforce/pull/1730 but happening in a 2nd place
> W-19055021 fix: no setting content-length in browser

- CHANGELOG.md
- package.json
- src/VERSION.ts
- src/http-api.ts
I think I missed the pjson version bump last time
> fix: cause release
